// Contract types crossing the Tauri invoke boundary are generated by ts-rs
// (pnpm codegen) from src-tauri/src/workspace/types.rs. Only purely frontend
// types live in this file.

export * from "./generated";
import type { SkillDiscoveryResultView } from "./generated";

// Frontend-facing alias: the Rust side names this SkillDiscoveryResultView.
export type SkillDiscoveryResult = SkillDiscoveryResultView;

export type WorkspaceTab = "targets" | "skills" | "mcp";

export type SkillSourceKind = "git" | "local";
