// Contract types crossing the Tauri invoke boundary are generated by ts-rs
// (pnpm codegen) from src-tauri/src/session/model.rs. The shared SourceApp
// union lives in the sessions feature where it was first defined; importing
// it keeps a single frontend source of truth for the agent enum.

export * from "./generated";
export type { SourceApp } from "../sessions/generated/SourceApp";
export type { SessionTokenUsage } from "../sessions/generated/SessionTokenUsage";
